spring.application.name=karma
# JWT
jwt.secret=b75a012a9c0e70b02bbdfe07e2511c8870bdebeb8e5cc9b48828e7f976444443
# DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/karma_staging
spring.datasource.username=postgres
spring.datasource.password=pgAdmin4
#JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true